Update util.py in stable diffusion to avoid Sizes of tensors error
In my experiments, I found that when I directly load an image, both in_paint.py and image_to_image.py encounter an error:

File "/root/autodl-tmp/SD/model/unet.py", line 178, in forward
    x = torch.cat([x, x_input_block.pop()], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 34 but got size 33 for tensor number 1 in the list.

This error can be avoided by modifying the load_img function in utils.py, specifically by changing the original multiple of 32 to a multiple of 64. This issue might be caused by the sd-v1-4.ckpt checkpoint.

I apologize if I may have mistakenly made two modifications on the master branch. Please disregard those changes, and this Pull-Request is the real debug version.